"""The TREND gate: Wilder ADX(14) on completed daily bars, house definition.

Mirrors the research engine exactly (research/ym_930_straddle_wide.py
`regime_tags`, itself the twin of the Pine ta.dmi gate the OOS exam ran
with): RMA smoothing (ewm alpha=1/14, adjust=False, seeded with the first
value), TR/DM with pandas-style NaN semantics at the series start, and the
gate for TODAY reads the ADX of the LAST COMPLETED session day.

Pure python, no dependencies — tests pin it bit-for-bit against a fixture
generated by the research implementation on real NQ daily bars.
"""
from __future__ import annotations

PERIOD = 14
THRESHOLD = 20.0


def _rma(values: list, period: int = PERIOD) -> list:
    """ewm(alpha=1/period, adjust=False) with pandas NaN semantics: leading
    None values yield None and the series seeds at the FIRST real value
    (this seed choice is why DX[0]=0/0 must stay None, not 0)."""
    out: list = []
    prev: float | None = None
    a = 1.0 / period
    for v in values:
        if v is None:
            out.append(None if prev is None else prev)
            continue
        prev = v if prev is None else prev + (v - prev) * a
        out.append(prev)
    return out


def adx_series(daily: list[dict]) -> list[float | None]:
    """Raw ADX(14) per completed daily bar (ASC order, keys h/l/c).
    Element i is the ADX as of bar i's close. None while warming up."""
    n = len(daily)
    if n < 2:
        return [None] * n
    h = [float(b["h"]) for b in daily]
    l = [float(b["l"]) for b in daily]
    c = [float(b["c"]) for b in daily]

    tr = [h[0] - l[0]]                       # first bar: no prev close
    plus = [0.0]
    minus = [0.0]
    for i in range(1, n):
        tr.append(max(h[i] - l[i], abs(h[i] - c[i - 1]), abs(l[i] - c[i - 1])))
        up, dn = h[i] - h[i - 1], l[i - 1] - l[i]
        plus.append(up if (up > dn and up > 0) else 0.0)
        minus.append(dn if (dn > up and dn > 0) else 0.0)

    atr = _rma(tr)
    p = _rma(plus)
    m = _rma(minus)
    dx: list = []
    for i in range(n):
        pdi = 100.0 * p[i] / atr[i] if atr[i] else 0.0
        mdi = 100.0 * m[i] / atr[i] if atr[i] else 0.0
        s = pdi + mdi
        dx.append(100.0 * abs(pdi - mdi) / s if s else None)  # 0/0 = NaN
    adx = _rma(dx)
    # warm-up: the research series carries NaN until enough bars exist; being
    # strict costs nothing — refuse a reading before 2*period bars
    return [adx[i] if i >= 2 * PERIOD else None for i in range(n)]


def trend_gate(daily: list[dict], threshold: float = THRESHOLD):
    """(is_trend, adx) for TODAY from completed daily bars ending YESTERDAY.
    is_trend is None when the series is too short to know — never guess."""
    s = adx_series(daily)
    if not s or s[-1] is None:
        return None, None
    return bool(s[-1] > threshold), round(s[-1], 2)
