"""The in-app ADX gate must match the research formula bit-for-bit on real
NQ daily bars (fixture generated by the pandas implementation)."""
from __future__ import annotations

import json
from pathlib import Path

from homebase.gate import adx_series, trend_gate

FIX = json.loads((Path(__file__).parent / "fixture_gate_nq2024.json").read_text())


def test_adx_matches_research_formula_on_real_nq():
    s = adx_series(FIX["bars"])
    for row in FIX["expected_tail"]:
        got, want = s[row["i"]], row["adx"]
        if want is None:
            assert got is None
        else:
            assert got is not None and abs(got - want) < 1e-9, \
                f"bar {row['i']}: {got} != {want}"


def test_trend_gate_reads_last_completed_bar():
    is_trend, adx = trend_gate(FIX["bars"])
    assert adx == round(FIX["expected_tail"][-1]["adx"], 2) == 22.42
    assert is_trend is True                      # 22.42 > 20


def test_gate_refuses_short_series():
    assert trend_gate(FIX["bars"][:20]) == (None, None)
    assert trend_gate([]) == (None, None)


def test_front_month_roll():
    import datetime as dt
    from homebase.symbols import front_month
    assert front_month("NQ", dt.date(2026, 9, 16)) == "NQZ6"   # rolled
    assert front_month("NQ", dt.date(2026, 9, 10)) == "NQU6"   # pre-roll
    assert front_month("NQ", dt.date(2026, 12, 14)) == "NQH7"  # year wrap
    assert front_month("YM", dt.date(2027, 1, 5)) == "YMH7"
