"""__DOC__

DRAFT for the Homebase Strategy Tester (__ROOT__ prop-portfolio pilot). Generated by gen_drafts.py from
template.py + families/__FAM__.py -- edit those, not this file.

Shape shared by every pp_* draft:
  * 1-minute engine bars are aggregated into `tf`-minute bars aligned to ET clock multiples of tf; a
    signal is evaluated ONLY when a tf bar CLOSES (completed bars only, no look-ahead). Level-setting
    families (orb, straddle, ib, lon_break, tod_drift) place resting orders at a clock time from completed
    1-minute bars.
  * Indicators (ATR, EMAs, family state) run over every tf bar since 00:00 ET of the day and reset each
    day (short warm-up for tf 15/30). Session objects (VWAP, counters) reset at each session start.
  * Sessions (ET): asia 00-03, london 03-08:25, nyam 09:30-11, mid 11-13:30, pm 13:30-15:58. sess=all trades
    each independently; flat at each session end; unfilled entries cancelled and no new entries in the
    last 5 minutes; one position at a time; max_tr entries per session.
  * Stops: atr = stop_val x ATR(14), pts = stop_val points, struct = the family's structural level (floored
    at 0.25 x ATR; families without one fall back to atr). Target = tgt_r x stop distance (0 = none).
    trail_atr / exit_bars are close-based market exits (exit_bars = tf closes since the fill). Prior-day H/L/C
    come from ctx.daily (whole archive day 18:00-16:59) and are unset on contract-roll days (ROLLS). Daily money
    rules are applied offline.
"""
from __future__ import annotations

import math
#@@IMPORTS

from homebase.strategies.base import Input, Strategy

#@@CONSTS

SESS = {"asia": (0, 10800), "london": (10800, 30300), "nyam": (34200, 39600),
        "mid": (39600, 48600), "pm": (48600, 57480), "news": (30570, 32400),
        "fomc": (50370, 52200)}                # seconds after 00:00 ET; news 08:29:30-09:00, fomc 13:59:30-14:30
ORDER = ("asia", "london", "nyam", "mid", "pm")
NS = 1_000_000_000


def _hms(s):
    return "%02d:%02d:%02d" % (s // 3600, s % 3600 // 60, s % 60)


def _sec(t):
    p = [int(x) for x in t.split(":")]
    return p[0] * 3600 + p[1] * 60 + (p[2] if len(p) > 2 else 0)


def _sid_at(s):
    for k in ORDER:
        if SESS[k][0] <= s < SESS[k][1]:
            return k
    return None


class __CLASS__(Strategy):
    id = "draft___NAME__"
    name = "__TITLE__"
    root = "__ROOT__"
    session_window = ("00:00", "16:10")
    bar_minutes = 1
    session_independent = True

    @classmethod
    def inputs(cls):
        return [
#@@INPUTS
        ]

    # ---- family hooks (defaults; the family block below overrides) --------------------------------------
    SPANS = ()          # extra EMA spans the family reads as self.E[span]
    WARM = 3            # min tf bars since 00:00 before any entry

    def fam_filter(self, ids):
        return ids

    def sess_on(self, s):
        """False = session s does not run today (families with day-dependent windows)."""
        return True

    def fam_day(self, ctx):
        pass

    def fam_session(self, ctx, s):
        pass

    def fam_update(self, ctx):
        pass

    def fam_signal(self, ctx):
        pass

    def fam_times(self):
        return []

    def fam_time(self, ctx, sec):
        pass

    # ---- schedule -----------------------------------------------------------------------------------------
    def sessions(self):
        s = self.p["sess"]
        return self.fam_filter(list(ORDER) if s == "all" else [s])

    def needs_daily(self):
        return True

    def times(self):
        ts = set(self.fam_times())
        for s in self.sessions():
            a, b = SESS[s]
            ts.update((_hms(a), _hms(b), _hms(b - 300)))
        return sorted(ts)

    def on_session(self, ctx):
        self.t0 = ctx.now_ns                       # ET midnight of the session date
        self.day = ctx.date.isoformat()
        self.held = 0                              # tf closes since the current position filled
        self.tf = int(self.p["tf"])
        self.step = self.tf * 60 * NS
        self.spans = sorted(set(self.SPANS) | {50})
        self.O, self.H, self.L, self.C, self.V, self.TR = [], [], [], [], [], []
        self.nb = 0
        self.atr = self.atr_p = None
        self.E, self.Ep = {}, {}
        self.cur = None
        self.M = []                                # completed 1m bars: (start_sec, o, h, l, c, v)
        self.vs, self.vr, self.vsid = [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], None
        self.sid, self.sn, self.n_ent = None, 0, 0
        self.orders = []                           # [order, expires_at_nb | None, counted]
        self.fill_ns, self.side, self.best = None, 0, 0.0
        self.onh = self.onl = None
        self.dl = ctx.daily
        d1 = self.dl[-1] if self.dl else None
        # prior-day levels are unusable on a contract-roll day: the prior bar is the old contract (~190 pts of carry)
        self.pdh, self.pdl, self.pdc = ((d1["h"], d1["l"], d1["c"]) if d1 and self.day not in ROLLS
                                        else (None, None, None))
        self._datr = None
        self.fam_day(ctx)

    def on_time(self, ctx, et_time):
        sec = _sec(et_time)
        self._sync(ctx)
        acts = [s for s in self.sessions() if self.sess_on(s)]
        for s in acts:
            a, b = SESS[s]
            if sec == b:
                ctx.flatten("time")
                self.orders, self.sid = [], None
            elif sec == b - 300 and self.sid == s:
                self._cancel(ctx)
        for s in acts:
            if sec == SESS[s][0]:
                self._start(ctx, s)
        self.fam_time(ctx, sec)

    def _start(self, ctx, s):
        self.sid, self.sn, self.n_ent, self.orders, self.fill_ns = s, 0, 0, [], None
        cut = 10800 if s == "london" else 34200 if s in ("nyam", "mid", "pm") else None
        r = self.rng(0, cut) if cut else None
        self.onh, self.onl = r if r else (None, None)
        self.fam_session(ctx, s)

    def _cancel(self, ctx):
        for r in self.orders:
            if r[0].status == "working":
                ctx.cancel(r[0])
        self.orders = []

    # ---- bars -----------------------------------------------------------------------------------------------
    def on_bar(self, ctx, bar):
        k = bar.start_ns // self.step
        if self.cur is not None and self.cur[0] != k:
            self._close(ctx)                        # last minute of the bucket had no print (before this bar's data)
        s = (bar.start_ns - self.t0) // NS
        self.M.append((s, bar.o, bar.h, bar.l, bar.c, bar.v))
        sid = _sid_at(s)
        if sid != self.vsid:
            self.vsid = sid
            self.vs = [0.0, 0.0, 0.0]
            if sid in ("asia", "london", "nyam"):
                self.vr = [0.0, 0.0, 0.0]          # rth anchor: 00:00 / 03:00 / 09:30
        if sid and bar.v > 0:
            v, tp = bar.v, (bar.h + bar.l + bar.c) / 3.0
            for a in (self.vs, self.vr):
                a[0] += v
                a[1] += v * tp
                a[2] += v * tp * tp
        cur = self.cur
        if cur is None:
            self.cur = [k, bar.o, bar.h, bar.l, bar.c, bar.v]
        else:
            if bar.h > cur[2]:
                cur[2] = bar.h
            if bar.l < cur[3]:
                cur[3] = bar.l
            cur[4] = bar.c
            cur[5] += bar.v
        if bar.end_ns % self.step == 0:
            self._close(ctx)

    def _close(self, ctx):
        k, o, h, l, c, v = self.cur
        self.cur = None
        end = ((k + 1) * self.step - self.t0) // NS          # nominal close (a late close never counts as in-session)
        n = self.nb
        tr = h - l if n == 0 else max(h - l, abs(h - self.C[-1]), abs(l - self.C[-1]))
        self.O.append(o)
        self.H.append(h)
        self.L.append(l)
        self.C.append(c)
        self.V.append(v)
        self.TR.append(tr)
        self.nb = n = n + 1
        self.atr_p = self.atr
        self.atr = sum(self.TR) / n if n <= 14 else (self.atr * 13.0 + tr) / 14.0
        for sp in self.spans:
            e = self.E.get(sp)
            self.Ep[sp] = e
            self.E[sp] = c if e is None else e + 2.0 / (sp + 1) * (c - e)
        s = self.sid
        inn = s is not None and SESS[s][0] < end <= SESS[s][1]
        if inn:
            self.sn += 1
        self.fam_update(ctx)
        if self._manage(ctx) or not inn:
            return
        if self.can_enter(ctx):
            self.fam_signal(ctx)

    # ---- state / gating -----------------------------------------------------------------------------------
    def _sync(self, ctx):
        for r in self.orders:
            o = r[0]
            if o.status == "filled" and not r[2]:
                r[2] = True
                self.n_ent += 1
                self.side, self.best, self.held = o.side, o.fill_px, 0
                self.fill_ns = o.fill_ms * 1_000_000
        if ctx.flat:
            self.fill_ns = None
        self.orders = [r for r in self.orders if r[0].status == "working"]

    def _manage(self, ctx):
        """Expire stale pending orders, then the close-based exits. True = flattened this close."""
        self._sync(ctx)
        for r in self.orders:
            if r[1] is not None and self.nb >= r[1]:
                ctx.cancel(r[0])
        if ctx.flat or self.fill_ns is None or ctx.now_ns <= self.fill_ns:
            return False
        c, sd = self.C[-1], self.side
        self.best = max(self.best, c) if sd > 0 else min(self.best, c)
        self.held += 1
        tr, eb = self.p["trail_atr"], self.p["exit_bars"]
        if tr > 0 and self.atr and (self.best - c) * sd > tr * self.atr:
            ctx.flatten("trail")
            return True
        if eb and self.held >= eb:
            ctx.flatten("bars")
            return True
        return False

    def can_enter(self, ctx):
        self._sync(ctx)
        if self.sid is None or self.atr is None or self.nb < self.WARM:
            return False
        if not ctx.flat or self.orders or self.n_ent >= self.p["max_tr"]:
            return False
        return ctx.now_ns - self.t0 < (SESS[self.sid][1] - 300) * NS

    def allowed(self, side):
        d = self.p["dir"]
        if d != "both" and d != side:
            return False
        sd = 1 if side == "long" else -1
        ft = self.p["f_trend"]
        if ft != "off":
            e, ep = self.E[50], self.Ep[50]
            if ep is None or (e - ep) * sd * (1 if ft == "with" else -1) <= 0:
                return False
        fv = self.p["f_vwap"]
        if fv != "off":
            w = self.vw()
            if w is None or (self.C[-1] - w[0]) * sd * (1 if fv == "with" else -1) <= 0:
                return False
        return True

    # ---- data helpers for families ----------------------------------------------------------------------
    def vw(self):
        """(session VWAP, volume-weighted stdev of typical price) or None."""
        return self._vw(self.vs)

    def vwr(self):
        """Same, anchored at the rth anchor (00:00 asia, 03:00 london, 09:30 NY sessions)."""
        return self._vw(self.vr)

    @staticmethod
    def _vw(a):
        if a[0] <= 0:
            return None
        m = a[1] / a[0]
        return m, math.sqrt(max(a[2] / a[0] - m * m, 0.0))

    def rng(self, a, b):
        """(high, low) of completed 1m bars inside [a, b) seconds after 00:00 ET, or None."""
        xs = [m for m in self.M if a <= m[0] and m[0] + 60 <= b]
        return (max(m[2] for m in xs), min(m[3] for m in xs)) if xs else None

    def mo(self, a):
        """Open of the first 1m bar starting at/after second a."""
        return next((m[1] for m in self.M if m[0] >= a), None)

    def mc(self, a, b):
        """Close of the last 1m bar starting inside [a, b)."""
        xs = [m[4] for m in self.M if a <= m[0] < b]
        return xs[-1] if xs else None

    def datr(self):
        """Wilder ATR(14) of the daily bars before today."""
        if self._datr is None and len(self.dl) >= 15:
            dl = self.dl
            trs = [max(dl[i]["h"] - dl[i]["l"], abs(dl[i]["h"] - dl[i - 1]["c"]),
                       abs(dl[i]["l"] - dl[i - 1]["c"])) for i in range(1, len(dl))]
            a = sum(trs[:14]) / 14.0
            for x in trs[14:]:
                a = (a * 13.0 + x) / 14.0
            self._datr = a
        return self._datr

    # ---- orders -------------------------------------------------------------------------------------------
    def _dist(self, ctx, ref, struct):
        m, a = self.p["stop_mode"], self.atr
        if m == "pts":
            d = self.p["stop_val"]
        elif m == "struct" and struct is not None:
            d = max(abs(ref - struct), 0.25 * a)
        else:
            d = self.p["stop_val"] * a
        return max(d, 2 * ctx.tick)

    def _tp(self, sd, ref, d, tp_px):
        if tp_px is not None:
            return tp_px if (tp_px - ref) * sd > 0 else None
        r = self.p["tgt_r"]
        return ref + sd * r * d if r > 0 else None

    def _mkt(self, ctx, side, struct=None, tp_px=None, ref=None):
        """Market entry at the signal close (or `ref`), brackets re-priced to the fill."""
        if not self.allowed(side):
            return
        sd = 1 if side == "long" else -1
        ref = self.C[-1] if ref is None else ref
        if tp_px is not None and (tp_px - ref) * sd < 2 * ctx.tick:
            return                                  # the target is already reached / behind us: no trade
        d = self._dist(ctx, ref, struct)
        ctx.move_brackets_to_fill = True
        o = ctx.market(side, sl=ref - sd * d, tp=self._tp(sd, ref, d, tp_px), ref=ref)
        self.orders.append([o, None, False])

    def _arm(self, ctx, legs, ttl=None, imm=False):
        """Resting stop entries [(side, price, struct, tp_px)], OCO when two. A leg whose level is already
        through the last print is skipped (it would fill at once) unless imm. ttl = tf bars it lives."""
        lp = ctx.last_price
        if lp is None:
            return
        os_ = []
        for side, px, struct, tp_px in legs:
            sd = 1 if side == "long" else -1
            if not self.allowed(side) or (not imm and (px - lp) * sd <= 0):
                continue
            d = self._dist(ctx, px, struct)
            ctx.move_brackets_to_fill = True
            os_.append(ctx.stop_entry(side, px, sl=px - sd * d, tp=self._tp(sd, px, d, tp_px)))
        if len(os_) == 2:
            ctx.oco(*os_)
        exp = self.nb + ttl if ttl else None
        self.orders += [[o, exp, False] for o in os_]

    # ---- family block (spliced from families/__FAM__.py) ---------------------------------------------------
#@@FAM
